# Generated by Django 4.1.5 on 2023-03-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_register',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
