# Generated by Django 4.1.5 on 2023-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_date_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(max_length=150, null=True, verbose_name='Номер телефона пользователя'),
        ),
    ]
