# Generated by Django 4.1.5 on 2023-03-22 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_user_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 3, 23, 0, 25, 0, 537645), verbose_name='Дата рождения'),
        ),
    ]
