# Generated by Django 4.1.5 on 2023-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profile',
            field=models.ImageField(blank=True, default='defaut_profile.png', null=True, upload_to='photo_profile/', verbose_name='Фото профиля пользователя'),
        ),
    ]
