# Generated by Django 4.1.5 on 2023-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.IntegerField(default=11, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
