# Generated by Django 4.1.5 on 2023-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_articul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parametrs',
            field=models.JSONField(default=list, null=True, verbose_name='Характеристики'),
        ),
    ]
