# Generated by Django 4.0.3 on 2023-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.CharField(max_length=100, verbose_name='Артикул'),
        ),
    ]
